version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - '5050:5050'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5050

  reverseproxy:
    build:
      context: .
      dockerfile: src/ReverseProxy/Dockerfile
    ports:
      - '5103:5103'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5103
    depends_on:
      - api
